export const asyncRoutes = [
/*  {
    code: 'Dashboard',
    name: '控制台',
    type: 'MENU',
    icon: 'i-fe:monitor',
    path: '/',
    component: '/src/views/home/index.vue',
    show: true,
    enable: true,
  },*/
  {
    code: 'UserManage',
    name: '用户管理',
    type: 'MENU',
    icon: 'i-fe:users',
    path: '/',
    component: '/src/views/home/index.vue',
    show: true,
    enable: true,
       children: [
         {
           id: 1,
           name: '用户列表管理',
           code: 'UserList',
           type: 'MENU',
           parentId: 2,
           path: '/user/list',
           redirect: null,
           component: '/src/views/user/list/index.vue',
           layout: null,
           keepAlive: true,
           method: null,
           description: null,
           show: true,
           enable: true,
           order: 1,
         },
         {
           id: 2,
           name: '用户提现管理',
           code: 'UserMgt',
           type: 'MENU',
           parentId: 2,
           path: '/pms/user',
           redirect: null,
           component: '/src/views/pms/user/index.vue',
           layout: null,
           keepAlive: true,
           method: null,
           description: null,
           show: true,
           enable: true,
           order: 1,
         },
         {
           id: 3,
           name: '代币变动明细',
           code: 'UserMgt',
           type: 'MENU',
           parentId: 2,
           path: '/pms/user',
           redirect: null,
           component: '/src/views/pms/user/index.vue',
           layout: null,
           keepAlive: true,
           method: null,
           description: null,
           show: true,
           enable: true,
           order: 1,
         },
         {
           id: 4,
           name: '用户行为日志',
           code: 'UserMgt',
           type: 'MENU',
           parentId: 2,
           path: '/pms/user',
           redirect: null,
           component: '/src/views/pms/user/index.vue',
           layout: null,
           keepAlive: true,
           method: null,
           description: null,
           show: true,
           enable: true,
           order: 1,
         },
         {
           id: 5,
           name: '实名认证管理',
           code: 'UserMgt',
           type: 'MENU',
           parentId: 2,
           path: '/pms/user',
           redirect: null,
           component: '/src/views/pms/user/index.vue',
           layout: null,
           keepAlive: true,
           method: null,
           description: null,
           show: true,
           enable: true,
           order: 1,
         },
       ],
  },
  {
    code: 'ListManage',
    name: '订单管理',
    type: 'MENU',
    icon: 'i-fe:trello',
    path: '/',
    component: '/src/views/home/index.vue',
    show: true,
    enable: true,
    children: [
      {
        id: 1,
        name: '订单列表',
        code: 'UserMgt',
        type: 'MENU',
        parentId: 2,
        path: '/pms/user',
        redirect: null,
        component: '/src/views/pms/user/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
    ],
  },
  {
    code: 'CardManage',
    name: '卡牌管理',
    type: 'MENU',
    icon: 'i-fe:framer',
    path: '/',
    component: '/src/views/home/index.vue',
    show: true,
    enable: true,
    children: [
      {
        id: 1,
        name: '卡牌发售管理',
        code: 'UserMgt',
        type: 'MENU',
        parentId: 2,
        path: '/pms/user',
        redirect: null,
        component: '/src/views/pms/user/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        id: 2,
        name: '会员卡牌管理',
        code: 'UserMgt',
        type: 'MENU',
        parentId: 2,
        path: '/pms/user',
        redirect: null,
        component: '/src/views/pms/user/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        id: 3,
        name: '卡片流转记录',
        code: 'UserMgt',
        type: 'MENU',
        parentId: 2,
        path: '/pms/user',
        redirect: null,
        component: '/src/views/pms/user/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
    ],
  },
  {
    code: 'MineSetting',
    name: '矿场配置',
    type: 'MENU',
    icon: 'i-me:awesome',
    path: '/',
    component: '/src/views/home/index.vue',
    show: true,
    enable: true,
    children: [
      {
        id: 1,
        name: '会员矿区管理',
        code: 'UserMgt',
        type: 'MENU',
        parentId: 2,
        path: '/pms/user',
        redirect: null,
        component: '/src/views/pms/user/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        id: 2,
        name: '矿场列表',
        code: 'UserMgt',
        type: 'MENU',
        parentId: 2,
        path: '/pms/user',
        redirect: null,
        component: '/src/views/pms/user/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      }
    ],
  },
  {
    code: 'AddressManage',
    name: '地址管理',
    type: 'MENU',
    icon: 'i-fe:sliders',
    path: '/',
    component: '/src/views/home/index.vue',
    show: true,
    enable: true,
    children: [
      {
        id: 1,
        name: '地址列表',
        code: 'UserMgt',
        type: 'MENU',
        parentId: 2,
        path: '/pms/user',
        redirect: null,
        component: '/src/views/pms/user/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      }
    ],
  },
  {
    code: 'ShoppingManagerSetting',
    name: '店长配置',
    type: 'MENU',
    icon: 'i-fe:coffee',
    path: '/',
    component: '/src/views/home/index.vue',
    show: true,
    enable: true,
    children: [
      {
        id: 1,
        name: '店长列表',
        code: 'UserMgt',
        type: 'MENU',
        parentId: 2,
        path: '/pms/user',
        redirect: null,
        component: '/src/views/pms/user/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      }
    ],
  },
  {
    code: 'WorkerManage',
    name: '工会管理',
    type: 'MENU',
    icon: 'i-fe:smile',
    path: '/',
    component: '/src/views/home/index.vue',
    show: true,
    enable: true,
    children: [
      {
        id: 1,
        name: '工会配置',
        code: 'UserMgt',
        type: 'MENU',
        parentId: 2,
        path: '/pms/user',
        redirect: null,
        component: '/src/views/pms/user/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        id: 2,
        name: '工会列表',
        code: 'UserMgt',
        type: 'MENU',
        parentId: 2,
        path: '/pms/user',
        redirect: null,
        component: '/src/views/pms/user/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        id: 3,
        name: '工会仓库',
        code: 'UserMgt',
        type: 'MENU',
        parentId: 2,
        path: '/pms/user',
        redirect: null,
        component: '/src/views/pms/user/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      }
    ],
  },
  {
    code: 'GameManager',
    name: '游戏管理',
    type: 'MENU',
    icon: 'i-fe:github',
    path: '/',
    component: '/src/views/home/index.vue',
    show: true,
    enable: true,
  },
  // {
  //   id: 2,
  //   name: '游戏记录',
  //   code: 'SysMgt',
  //   type: 'MENU',
  //   parentId: null,
  //   path: null,
  //   redirect: null,
  //   icon: 'i-fe:grid',
  //   component: null,
  //   layout: null,
  //   keepAlive: null,
  //   method: null,
  //   description: null,
  //   show: true,
  //   enable: true,
  //   order: 2,
  //   children: [
  //     {
  //       id: 4,
  //       name: '用户管理',
  //       code: 'UserMgt',
  //       type: 'MENU',
  //       parentId: 2,
  //       path: '/pms/user',
  //       redirect: null,
  //       icon: 'i-fe:user',
  //       component: '/src/views/pms/user/index.vue',
  //       layout: null,
  //       keepAlive: true,
  //       method: null,
  //       description: null,
  //       show: true,
  //       enable: true,
  //       order: 3,
  //     },
  //   ],
  // },
  // {
  //   id: 2,
  //   name: '系统管理',
  //   code: 'SysMgt',
  //   type: 'MENU',
  //   parentId: null,
  //   path: null,
  //   redirect: null,
  //   icon: 'i-fe:grid',
  //   component: null,
  //   layout: null,
  //   keepAlive: null,
  //   method: null,
  //   description: null,
  //   show: true,
  //   enable: true,
  //   order: 2,
  //   children: [
  //     {
  //       id: 1,
  //       name: '资源管理',
  //       code: 'Resource_Mgt',
  //       type: 'MENU',
  //       parentId: 2,
  //       path: '/pms/resource',
  //       redirect: null,
  //       icon: 'i-fe:list',
  //       component: '/src/views/pms/resource/index.vue',
  //       layout: null,
  //       keepAlive: null,
  //       method: null,
  //       description: null,
  //       show: true,
  //       enable: true,
  //       order: 1,
  //     },
  //     {
  //       id: 3,
  //       name: '角色管理',
  //       code: 'RoleMgt',
  //       type: 'MENU',
  //       parentId: 2,
  //       path: '/pms/role',
  //       redirect: null,
  //       icon: 'i-fe:user-check',
  //       component: '/src/views/pms/role/index.vue',
  //       layout: null,
  //       keepAlive: null,
  //       method: null,
  //       description: null,
  //       show: true,
  //       enable: true,
  //       order: 2,
  //       children: [
  //         {
  //           id: 5,
  //           name: '分配用户',
  //           code: 'RoleUser',
  //           type: 'MENU',
  //           parentId: 3,
  //           path: '/pms/role/user/:roleId',
  //           redirect: null,
  //           icon: 'i-fe:user-plus',
  //           component: '/src/views/pms/role/role-user.vue',
  //           layout: 'full',
  //           keepAlive: null,
  //           method: null,
  //           description: null,
  //           show: false,
  //           enable: true,
  //           order: 1,
  //         },
  //       ],
  //     },
  //     {
  //       id: 4,
  //       name: '用户管理',
  //       code: 'UserMgt',
  //       type: 'MENU',
  //       parentId: 2,
  //       path: '/pms/user',
  //       redirect: null,
  //       icon: 'i-fe:user',
  //       component: '/src/views/pms/user/index.vue',
  //       layout: null,
  //       keepAlive: true,
  //       method: null,
  //       description: null,
  //       show: true,
  //       enable: true,
  //       order: 3,
  //       children: [
  //         {
  //           id: 13,
  //           name: '创建新用户',
  //           code: 'AddUser',
  //           type: 'BUTTON',
  //           parentId: 4,
  //           path: null,
  //           redirect: null,
  //           icon: null,
  //           component: null,
  //           layout: null,
  //           keepAlive: null,
  //           method: null,
  //           description: null,
  //           show: true,
  //           enable: true,
  //           order: 1,
  //         },
  //       ],
  //     },
  //   ],
  // },
]
