export const asyncRoutes = [
  {
    code: 'Dashboard',
    name: '控制台',
    type: 'MENU',
    icon: 'i-fe:monitor',
    path: '/',
    component: '/src/views/home/index.vue',
    show: true,
    enable: true,
  },
  {
    code: 'UserManage',
    name: '用户管理',
    type: 'MENU',
    icon: 'i-fe:users',
    path: null,
    component: '/src/views/home/index.vue',
    show: true,
    enable: true,
    children: [
      {
        name: '用户列表管理',
        code: 'UserList',
        type: 'MENU',
        path: '/user/list',
        redirect: null,
        component: '/src/views/user/list/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        name: '宝石变动明细',
        code: 'UserBalanceLog',
        type: 'MENU',
        path: '/user/balance-log',
        redirect: null,
        component: '/src/views/user/balance-log/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        name: '用户行为日志',
        code: 'UserOperationLog',
        type: 'MENU',
        path: '/user/operation-log',
        redirect: null,
        component: '/src/views/user/operation-log/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        name: '实名认证管理',
        code: 'UserCert',
        type: 'MENU',
        path: '/user/cert',
        redirect: null,
        component: '/src/views/user/cert/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
    ],
  },
  {
    code: 'CardManage',
    name: '卡牌管理',
    type: 'MENU',
    icon: 'i-fe:framer',
    path: null,
    component: '/src/views/home/index.vue',
    show: true,
    enable: true,
    children: [
      {
        name: '卡牌发售管理',
        code: 'CardList',
        type: 'MENU',
        path: '/card/list',
        redirect: null,
        component: '/src/views/card/list/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        name: '会员卡牌管理',
        code: 'CardUser',
        type: 'MENU',
        path: '/card/user',
        redirect: null,
        component: '/src/views/card/user/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        name: '卡片流转记录',
        code: 'CardLog',
        type: 'MENU',
        path: '/card/log',
        redirect: null,
        component: '/src/views/card/log/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
    ],
  },
  {
    code: 'MineSetting',
    name: '矿场配置',
    type: 'MENU',
    icon: 'i-me:awesome',
    path: null,
    component: null,
    show: true,
    enable: true,
    children: [
      {
        name: '基础配置',
        code: 'MineBasicConfig',
        type: 'MENU',
        path: '/mine/basic-config',
        redirect: null,
        component: '/src/views/mine/basic-config/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        name: '矿场列表',
        code: 'MineList',
        type: 'MENU',
        path: '/mine/list',
        redirect: null,
        component: '/src/views/mine/list/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        name: '会员矿区管理',
        code: 'MineUser',
        type: 'MENU',
        path: '/mine/user',
        redirect: null,
        component: '/src/views/mine/user/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
    ],
  },
  // {
  //   code: 'AddressManage',
  //   name: '地址管理',
  //   type: 'MENU',
  //   icon: 'i-fe:sliders',
  //   path: '/',
  //   component: '/src/views/home/index.vue',
  //   show: true,
  //   enable: true,
  //   children: [
  //     {
  //       name: '地址列表',
  //       code: 'UserMgt',
  //       type: 'MENU',
  //       parentId: 2,
  //       path: '/pms/user',
  //       redirect: null,
  //       component: '/src/views/pms/user/index.vue',
  //       layout: null,
  //       keepAlive: true,
  //       method: null,
  //       description: null,
  //       show: true,
  //       enable: true,
  //       order: 1,
  //     }
  //   ],
  // },
  {
    code: 'StoreManagerSetting',
    name: '店长管理',
    type: 'MENU',
    icon: 'i-fe:coffee',
    path: '/store',
    component: '/src/views/store/index.vue',
    show: true,
    enable: true,
  },
  {
    code: 'GameManager',
    name: '游戏管理',
    type: 'MENU',
    icon: 'i-fe:github',
    path: '/',
    component: '/src/views/home/index.vue',
    show: true,
    enable: true,
  },
  {
    code: 'AppManage',
    name: '运营配置',
    type: 'MENU',
    icon: 'i-fe:users',
    path: '/',
    component: '/src/views/home/index.vue',
    show: true,
    enable: true,
    children: [
      {
        name: '基础配置',
        code: 'BasicConfig',
        type: 'MENU',
        parentId: 2,
        path: '/app/basic-config',
        redirect: null,
        component: '/src/views/app/basic-config/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        name: '第三方配置',
        code: 'ThirdConfig',
        type: 'MENU',
        path: '/app/third-config',
        redirect: null,
        component: '/src/views/app/third-config/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
    ],
  },
  {
    code: 'SystemManage',
    name: '系统管理',
    type: 'MENU',
    icon: 'i-fe:users',
    path: '/',
    component: '/src/views/home/index.vue',
    show: true,
    enable: true,
    children: [
      {
        name: '用户管理',
        code: 'SysUser',
        type: 'MENU',
        parentId: 2,
        path: '/sys/user',
        redirect: null,
        component: '/src/views/pms/user/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        name: '角色管理',
        code: 'SysRole',
        type: 'MENU',
        parentId: 2,
        path: '/sys/role',
        redirect: null,
        component: '/src/views/pms/role/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
      {
        name: '资源管理',
        code: 'SysResource',
        type: 'MENU',
        parentId: 2,
        path: '/sys/resource',
        redirect: null,
        component: '/src/views/pms/resource/index.vue',
        layout: null,
        keepAlive: true,
        method: null,
        description: null,
        show: true,
        enable: true,
        order: 1,
      },
    ],
  },
  // {
  //   id: 2,
  //   name: '游戏记录',
  //   code: 'SysMgt',
  //   type: 'MENU',
  //   parentId: null,
  //   path: null,
  //   redirect: null,
  //   icon: 'i-fe:grid',
  //   component: null,
  //   layout: null,
  //   keepAlive: null,
  //   method: null,
  //   description: null,
  //   show: true,
  //   enable: true,
  //   order: 2,
  //   children: [
  //     {
  //       id: 4,
  //       name: '用户管理',
  //       code: 'UserMgt',
  //       type: 'MENU',
  //       parentId: 2,
  //       path: '/pms/user',
  //       redirect: null,
  //       icon: 'i-fe:user',
  //       component: '/src/views/pms/user/index.vue',
  //       layout: null,
  //       keepAlive: true,
  //       method: null,
  //       description: null,
  //       show: true,
  //       enable: true,
  //       order: 3,
  //     },
  //   ],
  // },
  // {
  //   id: 2,
  //   name: '系统管理',
  //   code: 'SysMgt',
  //   type: 'MENU',
  //   parentId: null,
  //   path: null,
  //   redirect: null,
  //   icon: 'i-fe:grid',
  //   component: null,
  //   layout: null,
  //   keepAlive: null,
  //   method: null,
  //   description: null,
  //   show: true,
  //   enable: true,
  //   order: 2,
  //   children: [
  //     {
  //       id: 1,
  //       name: '资源管理',
  //       code: 'Resource_Mgt',
  //       type: 'MENU',
  //       parentId: 2,
  //       path: '/pms/resource',
  //       redirect: null,
  //       icon: 'i-fe:list',
  //       component: '/src/views/pms/resource/index.vue',
  //       layout: null,
  //       keepAlive: null,
  //       method: null,
  //       description: null,
  //       show: true,
  //       enable: true,
  //       order: 1,
  //     },
  //     {
  //       id: 3,
  //       name: '角色管理',
  //       code: 'RoleMgt',
  //       type: 'MENU',
  //       parentId: 2,
  //       path: '/pms/role',
  //       redirect: null,
  //       icon: 'i-fe:user-check',
  //       component: '/src/views/pms/role/index.vue',
  //       layout: null,
  //       keepAlive: null,
  //       method: null,
  //       description: null,
  //       show: true,
  //       enable: true,
  //       order: 2,
  //       children: [
  //         {
  //           id: 5,
  //           name: '分配用户',
  //           code: 'RoleUser',
  //           type: 'MENU',
  //           parentId: 3,
  //           path: '/pms/role/user/:roleId',
  //           redirect: null,
  //           icon: 'i-fe:user-plus',
  //           component: '/src/views/pms/role/role-user.vue',
  //           layout: 'full',
  //           keepAlive: null,
  //           method: null,
  //           description: null,
  //           show: false,
  //           enable: true,
  //           order: 1,
  //         },
  //       ],
  //     },
  //     {
  //       id: 4,
  //       name: '用户管理',
  //       code: 'UserMgt',
  //       type: 'MENU',
  //       parentId: 2,
  //       path: '/pms/user',
  //       redirect: null,
  //       icon: 'i-fe:user',
  //       component: '/src/views/pms/user/index.vue',
  //       layout: null,
  //       keepAlive: true,
  //       method: null,
  //       description: null,
  //       show: true,
  //       enable: true,
  //       order: 3,
  //       children: [
  //         {
  //           id: 13,
  //           name: '创建新用户',
  //           code: 'AddUser',
  //           type: 'BUTTON',
  //           parentId: 4,
  //           path: null,
  //           redirect: null,
  //           icon: null,
  //           component: null,
  //           layout: null,
  //           keepAlive: null,
  //           method: null,
  //           description: null,
  //           show: true,
  //           enable: true,
  //           order: 1,
  //         },
  //       ],
  //     },
  //   ],
  // },
]
